name: apiverve_carddeckshuffler
description: Card Deck Shuffler is a tool for shuffling standard playing card decks. It supports multiple decks, optional jokers, and different shuffling methods to generate randomized card sequences for games and simulations.
version: 1.1.14
homepage: https://apiverve.com/marketplace/carddeckshuffler?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/carddeckshuffler-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
